apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pediagents.fullname" . }}-secret-reader-binding
  labels:
    app.kubernetes.io/name: {{ include "pediagents.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pediagents.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "pediagents.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
