{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pediagents.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "pediagents.name" . }}
{{- end }}
