apiVersion: v1
kind: Service
metadata:
  name: {{ include "pediagents.fullname" . }}-orchestrator-svc
  labels:
    app: {{ include "pediagents.fullname" . }}-orchestrator
spec:
  selector:
    app: {{ include "pediagents.fullname" . }}-orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
