apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pedi-orchestrator.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "pedi-orchestrator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pedi-orchestrator.name" . }}
      component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pedi-orchestrator.name" . }}
        component: worker
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "pedi-orchestrator.fullname" . }}-sa
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pedi-orchestrator.fullname" . }}-secret
                  key: database_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pedi-orchestrator.fullname" . }}-secret
                  key: redis_url
            - name: METRICS_PORT
              value: "9090"
            - name: OTEL_COLLECTOR_URL
              value: ""
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
