apiVersion: v1
kind: Service
metadata:
  name: {{ include "pedi-orchestrator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pedi-orchestrator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 9000 }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pedi-orchestrator.name" . }}
    component: orchestrator
