{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pedi-orchestrator.fullname" . }}-sa
  labels:
    app.kubernetes.io/name: {{ include "pedi-orchestrator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
