apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "medgemma.fullname" . }}-role
  labels:
    {{ include "medgemma.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "medgemma.fullname" . }}-rb
  labels:
    {{ include "medgemma.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "medgemma.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "medgemma.fullname" . }}
    namespace: {{ .Release.Namespace }}
