{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pediagents.name" . }}-rolebinding
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pediagents.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pediagents.serviceAccountName" . }}
    namespace: {{ default .Release.Namespace .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "pediagents.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
