{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pediagents.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pediagents.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
